import React from 'react';
import ReactMarkdown from 'react-markdown';
import { FileText, Download, RotateCcw } from 'lucide-react';

interface ReportDisplayProps {
  markdown: string;
  onReset: () => void;
}

export const ReportDisplay: React.FC<ReportDisplayProps> = ({ markdown, onReset }) => {

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden animate-fade-in">
      <div className="bg-slate-900 text-white p-6 flex justify-between items-center sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-indigo-500 rounded-lg">
            <FileText className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-bold">Damage Assessment Report</h2>
            <p className="text-slate-400 text-sm">Generated by AI Analysis</p>
          </div>
        </div>
        <div className="flex gap-2">
           <button
            onClick={onReset}
            className="p-2 hover:bg-slate-800 rounded-lg text-slate-300 transition-colors flex items-center gap-2 text-sm"
          >
            <RotateCcw className="w-4 h-4" />
            <span className="hidden sm:inline">New Inspection</span>
          </button>
          <button
            onClick={handlePrint}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 rounded-lg font-medium transition-colors flex items-center gap-2 text-sm shadow-lg shadow-indigo-900/50"
          >
            <Download className="w-4 h-4" />
            <span>Export / Print</span>
          </button>
        </div>
      </div>

      <div className="p-8 prose prose-slate max-w-none">
        <ReactMarkdown
            components={{
                h1: ({node, ...props}) => <h1 className="text-3xl font-extrabold text-slate-800 mb-6 pb-2 border-b border-slate-200" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4" {...props} />,
                h3: ({node, ...props}) => <h3 className="text-xl font-semibold text-slate-700 mt-6 mb-3" {...props} />,
                ul: ({node, ...props}) => <ul className="list-disc pl-6 space-y-2 mb-4 text-slate-600" {...props} />,
                ol: ({node, ...props}) => <ol className="list-decimal pl-6 space-y-2 mb-4 text-slate-600" {...props} />,
                li: ({node, ...props}) => <li className="" {...props} />,
                p: ({node, ...props}) => <p className="text-slate-600 leading-relaxed mb-4" {...props} />,
                strong: ({node, ...props}) => <strong className="font-bold text-slate-900" {...props} />,
                table: ({node, ...props}) => <div className="overflow-x-auto my-6 rounded-lg border border-slate-200"><table className="min-w-full divide-y divide-slate-200" {...props} /></div>,
                thead: ({node, ...props}) => <thead className="bg-slate-50" {...props} />,
                tbody: ({node, ...props}) => <tbody className="bg-white divide-y divide-slate-200" {...props} />,
                tr: ({node, ...props}) => <tr className="" {...props} />,
                th: ({node, ...props}) => <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider" {...props} />,
                td: ({node, ...props}) => <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-600" {...props} />,
                blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-indigo-500 pl-4 italic text-slate-500 my-4" {...props} />,
            }}
        >
          {markdown}
        </ReactMarkdown>
      </div>

      <div className="bg-slate-50 p-4 text-center text-xs text-slate-400 border-t border-slate-100">
        AI generated report. Verify all findings manually.
      </div>
    </div>
  );
};
